### ISSUE TITLE
Thank you for the SPM toolbox and questions regarding the use of toolbox

### ISSUE THREAD

**Issue by PouyanMehryar** [0todd0000/spm1dmatlab#13] opened 2016-02-15 23:54 UTC
I have a few questions that I would really appreciate it if you be able to answer please.  

I used the non negative matrix factorisation to decompose a high dimensional EMG signal to two low dimensional components. (1)  Muscle synergy which represents relative weighting of each muscle within the corresponding synergy (2) Activation coefficient (profile) which represents the timing of muscle synergy being active over time (gait cycle). 

I compared two groups; one as control and the other as case group. 

For comparing the activation coefficient profiles between the two groups, a two way SPM t-test was performed. So I am not really sure if this is the correct test to do as I have seen in some of your papers that you used Hotellings T2 test??

My next question is the plot on the right shows the difference between the two groups. Firstly, is this the difference in the mean of activation profiles of the two groups? 

Secondly, what is the difference when significant difference occur below the t* or above the t*? 

Thirdly, for the areas that are not significantly different, what does it mean when the curve is above or below the baseline (see the right figure attached in this issue)? Do the above the baseline and below baseline mean positive correlation and negative correlation between the two groups, receptively?

![spm3](https://cloud.githubusercontent.com/assets/17261178/13063482/7700f276-d440-11e5-906d-bb40aa3d8674.JPG)

![spm3](https://cloud.githubusercontent.com/assets/17261178/13063485/78bb52b4-d440-11e5-8fe6-ce3583df6494.JPG)

Thank you in advance for your response.

**Comment by 0todd0000** [comment] 2016-02-16 00:43
Hi Pouyan,

Thank you very much for the positive feedback, much appreciated!

A two-sample t test should be used if your null hypothesis and data are univariate (scalar) and a two-sample Hotelling's T<sup>2</sup> test should be used if your null hypothesis and data are multivariate (vector).  In this case it sounds like your data are multivariate because:
* There are two dependent variables (synergy weighting, activation)  and
* Your null hypothesis implicitly pertains to both variables (because you haven't proposed a specific hypothesis regarding just one of the variables).


The **SPM{t}** in the plots on the right is simply the t value continuum (or t value trajectory or t value waveform, etc.), and the t value is effectively:

```math
t = (mean difference) / (normalized variance)
```

In this case positive and negative t values indicate where the Amputee values are greater and less than the Healthy values, respectively. Thus t values above the upper threshold suggest significantly greater Amputee values, and t values below the lower threshold suggest significantly greater Healthy values. You can create the opposite interpretation by swapping the Healthy and Amputee order like this:

```python
t = spm1d.stats.ttest2(yAmputee, yHealthy)
t = spm1d.stats.ttest2(yHealthy, yAmputee)
``` 

For regions of the **SPM{t}** which fail to cross the threshold, the interpretation is the same as in all classical hypothesis tests:  *insufficient evidence to reject the null hypothesis*.  In this case the null hypothesis is: *no inter-group mean trajectory differences*. If that null hypothesis were true, and the observed mean differences were produced by smooth but purely random 1D trajectories, then we would expect to see t values close to zero with very high probability, but we'd expect to see t values above/below the critical thresholds with a probability of alpha.  More simply, in areas which do not cross the threshold the mean difference is not large relative to the variance.

Cheers,

Todd

**Comment by PouyanMehryar** [comment] 2016-02-16 01:23
Thank you for your prompt response. 

Actually, I am only comparing the activation profiles as I used another statistical analysis for my muscle synergies. Therefore, the results shown are related to the activation profiles of the control and case groups. My null hypothesis was there is no a significant difference in the mean activation profiles of the two groups. 

** In this case, Is it correct to use the two-sample t test?**

I used 
`SPM1=` spm1d_stats_ttest2(C1_healthy, C1_amputee); `
which I believe indicates that the upper threshold suggests significantly greater Amputee values, and t values below the lower threshold suggests significantly greater Healthy values. Am I correct?

I have a couple of questions regarding one your comments; 
In SPM{t}, when the amputee group activation profile is positive, Does it mean at some percentage of the gait cycle its amplitude exceed the control group but it is not statistically significant? 

Can this positive and negative t values on the right fig be interpreted as positive and negative correlation between healthy and amputee subjects??? So if the data is positive then there is a positive correlation between the data of healthy and amputee considering the amputee values are greater.
 

and Sorry I sent the same photo twice.
![spm1](https://cloud.githubusercontent.com/assets/17261178/13064171/3ce62126-d448-11e5-9d82-1e4caebad641.JPG)

**Comment by 0todd0000** [comment] 2016-02-16 03:16
Yes, if your data are univariate then you should use a univariate test.

If you are using "spm1d_stats_ttest2" then you are probably using an old version of the software.  Please download the most recent version, in which the same function is:  "spm1d.stats.ttest2".

If the t value is not zero it implies that the mean difference is not zero. In a two-sample t test t values shouldn't be interpreted as a correlation. Instead negative and positive t values imply negative and positive mean differences.

Todd

**Comment by 0todd0000** [comment] 2016-02-23 06:23
Hi Pouyan,  it has been a week so I'm closing this issue, but please feel free to continue discussion here or to create a new issue if anything is unclear.  Cheers, Todd

**Closed by 0todd0000** 2016-02-23 06:23 UTC

**Comment by PouyanMehryar** [comment] 2016-02-23 09:49
I would like to thank you for your kind supports.

Kind regards,

On Tue, Feb 23, 2016 at 6:23 AM, Todd Pataky <notifications@github.com>
wrote:

> Closed #13 <https://github.com/0todd0000/spm1dmatlab/issues/13>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/0todd0000/spm1dmatlab/issues/13#event-561075261>.
>



-- 

*Pouyan Mehryar (Master of Mechanical and Medical Engineering)*

PhD student in Neuro-Engineering - Institute of Design, Robotics and
Optimisation (iDRO) - School of Mechanical Engineering - University of
Leeds - Leeds - LS2 9JT - UK



T +44 7956785239

E mnpm@leeds.ac.uk



Visit our web site *http://www.engineering.leeds.ac.uk/idro/
<http://www.engineering.leeds.ac.uk/idro/>*

Institute of iDRO

**Comment by PouyanMehryar** [comment] 2017-08-10 00:34
Hi Tod, 

Thank you for the great toolbox.
I have several questions regarding SPM Hotelling T-test and anova 1D. 

Background:
Knowing that the Gaussian vector-field more appropriately models variance in multi-muscle EMG time series than each EMG waveform and considering my non-directed hypothesis is ‘There is no difference between the muscles of lower limb of group A and group B at different speeds (slow, normal and fast), I employ a SPM Hotelling’s T2 statistic. Note, I considered Group A fast Vs Group B fast; Group A normal Vs Group B normal and Group A slow Vs Group B slow. The EMG time series were analysed as a 12-component vector-field I = 12 (nom. Muscles), J = 24 (nom. Subjects A and B), Q = 100 (i.e. group A = [13x100x12] and group B = [11x100x12] at each speed). The result showed significant difference between group A and group B at fast speed (fig1). Two suprathreshold clusters were found. This only indicates there are 2 regions where the statistically significant differences occur but it does not indicate which muscles are different. Therefore, I performed two-sample SPM t-test on individual muscles in order to compare the 2 groups with apha = 0.05 (fig 2). The t-test indicated that triceps surae were significantly different which may have resulted in intersubjective difference. 

![hotelling_t_test](https://user-images.githubusercontent.com/17261178/29149052-65d8eec6-7d69-11e7-868e-da41f290f870.png)


![gm_t_test](https://user-images.githubusercontent.com/17261178/29149101-b0846d60-7d69-11e7-8b32-81d70986561f.png)

Q1: Knowing that non-directed hypotheses should not assume EMG waveform independence, in this case, the two-sample t-test with a significant level of 0.05 provides additional explanation for the significant vector-field analysis. Is this test appropriate for the further investigation of the data or  Hotelling t-test is enough?  

Q2: Do I need to adopt any correction to reduce the significant level (i.e. sidak corrected threshold)? How could I implement it in matlab? 

Q3: If there are 3 different groups rather than 2 which test should be to be implemented?

Q3: Along the same line, I investigated the difference in activation of each muscle between 3 speeds in group B using Anova1D. That is, groups B consists of 11 subjects who performed 3 to 5 trials of walking at slow, normal and fast. 12 muscles were recorded throughout. I used all the trials from each subject and each muscle to compare between speeds 
Muscle_1_Fast_walking = [33 x 100] (11 subjects each performed 3 trials)
Muscle_1_Normal_walking = [44 x 100] (11 subjects each performed 4trials)
Muscle_1_Slow_walking = [35 x 100] 
Furthermore, I used anova post-hoc to investigate the results further. I wonder if this approach is correct to compare between different speeds within the same population? My only concern is that this method does not consider inter-muscle covariance but is there any other approach to employ which consider covariance in this scenario? 

Q4: How can I change the location of alpha and p – value and make the threshold line thicker in the graph?


I really appreciate your help.

**Comment by PouyanMehryar** [comment] 2017-08-11 00:23
Dear Tod, 

Sorry to write another post before getting the answer to the previous one. The following questions are related to the above post.

As I mentioned in Q3 above: I have another group called group C. Let's say there is no other way to consider all 3 groups (Group A, Group B, and Group C) at the same time and individual analyses needed to be done. 
 I have tried to perform non-parametric and parametric SPM Hotelling’s T2 statistic between group A = [13x100x12] and group C = [3x100x12] however the results are very strange. 

![image](https://user-images.githubusercontent.com/17261178/29197080-ba4c624a-7e30-11e7-92e6-09b8a225d50d.png)

Q5: Why the critical random field theory threshold is so large? 

When the EMG signals from the other leg in group C [3x100x8] were compared with group A [13x100x8] (the number of muscles was reduced to 8) the following results were obtained:
![image](https://user-images.githubusercontent.com/17261178/29197244-e5adcc2a-7e31-11e7-852a-7b6b76523c4e.png)

Q6: The parametric figure seems to be close to the threshold but the non-parametric one is far off. How could one interpret this dataset? Is there any way to do normality test for SPM Hotelling’s T2 statistic?

Thank you in advance for your response!

**Comment by 0todd0000** [comment] 2017-08-11 22:15
Hello,

> Q1: Knowing that non-directed hypotheses should not assume EMG waveform independence, in this case, the two-sample t-test with a significant level of 0.05 provides additional explanation for the significant vector-field analysis. Is this test appropriate for the further investigation of the data or Hotelling t-test is enough?

Univariate *post hoc* tests (i.e. t tests) are fine but only insofar as they agree with the multivariate (Hotelling's T2) results.  There are more robust multivariate *post hoc* procedures that will agree precisely with the original multivariate results. Those involve coordinate system transformations, similar to PCA, but these are not yet available in **spm1d**.


> Q2: Do I need to adopt any correction to reduce the significant level (i.e. sidak corrected threshold)? How could I implement it in matlab?

Since the *post hoc* tests are not exact I think it's fine to do anything you like provided the results do not disagree with the original multivariate results.  A Sidak / Bonferroni correction, for example, is a good first approximation, but this is only accurate when the vector components are independent.


> Q3: If there are 3 different groups rather than 2 which test should be to be implemented?

One-way MANOVA  (spm1d.stats.manova1). However, the design you describe above actually sounds like two-way MANOVA, where the first and second factors are "AB" and "speed", respectively.  Two-way MANOVA is not yet supported in **spm1d**.

> Q3: Along the same line, I investigated the difference in activation of each muscle between 3 speeds in group B using Anova1D. That is, groups B consists of 11 subjects who performed 3 to 5 trials of walking at slow, normal and fast. 12 muscles were recorded throughout. I used all the trials from each subject and each muscle to compare between speeds
> Muscle_1_Fast_walking = [33 x 100] (11 subjects each performed 3 trials)
> Muscle_1_Normal_walking = [44 x 100] (11 subjects each performed 4trials)
> Muscle_1_Slow_walking = [35 x 100]
> Furthermore, I used anova post-hoc to investigate the results further. I wonder if this approach is correct to compare between different speeds within the same population? My only concern is that this method does not consider inter-muscle covariance but is there any other approach to employ which consider covariance in this scenario?

I think one-way MANOVA would be OK for this analysis.


> Q4: How can I change the location of alpha and p – value and make the threshold line thicker in the graph?

Those options are not directly supported with the **spm1d** plotting interface;  the plotting interface is meant to be rudimentary, and customizations (if desired) should be done manually.  Please use the the appropriate values inside the SPM variable (e.g. spm.zstar to plot the threshold).  


> Q5: Why the critical random field theory threshold is so large?

This is more of a multivariate issue than a random field theory issue. Your variables are [13x100x12] and [3x100x12], implying 12 vector components but a sample size of just 16.  The covariance matrix at each point in time is 12x12 and contains 144 values, approximately half of which are unique.  A sample size of 16 is far too small to be able to accurately estimate the covariance components and, since variance is poorly estimated, the threshold must be high.  This is analogous to a t test for which you only have three observations;  three observations is far too few to accurately estimate variance, so the threshold must be high to retain alpha=0.05 across an infinite number of tests.

> Q6: The parametric figure seems to be close to the threshold but the non-parametric one is far off. How could one interpret this dataset? Is there any way to do normality test for SPM Hotelling’s T2 statistic?

I would be reluctant to interpret these results because the sample size is too small.  I suspect that the differences between the parametric and non-parametric results stem from sample size rather than non-normality.  Multivariate normality tests are indeed possible but not in the current version of **spm1d**.  They will be supported in future versions.

In general, when conducting multivariate analysis it's important to ensure that the sample size is sufficiently large for accurate covariance component estimations. An internet search for "multivariate sample size" should return many relevant results.  For example, from the link below one person recommends a sample size of 5*m*, where *m* is the number of estimated covariance components.  If you have 12 vector components, there are 78 separate covariance components, implying a sample size of 390.  However, note that most journals would regard a sample size of five to be quite small, so I'd personally aim for about 10*m*.
https://stats.stackexchange.com/questions/10079/rules-of-thumb-for-minimum-sample-size-for-multiple-regression

Todd

**Comment by PouyanMehryar** [comment] 2017-08-12 11:48
Thank you for your comprehensive explanations. I am sorry but I have some more follow up questions that I'd really appreciate your help, please.

reply to Q1> _**__only insofar as they agree with the multivariate (Hotelling's T2) results. **__

Q1A: Does it mean when vector field SPM{T2} result was significant then it is expected when post-hoc t-test is performed at least one of the 12 muscles (vector field components) shows the significant difference in the regions where SPM{T2} supra-threshold cluster occurred?

Reply to Q2: _**> A Sidak / Bonferroni correction, for example, is a good first approximation,**_ 
I used alpha = 0.05 without any correction and results agree with the SPM{T2}, However, I have seen in several papers the alpha level was corrected (sidak /Bonferroni). My question is due to the limitation to do multivariate post hoc, is it justifiable to use the same alpha level (= 0.05) or the correction needs to be implemented (Q2A)? 
if the correction needs to be done then is the following the right procedure (Q2B)? (nTests implies two groups then = 2). The t-test with correct p-critical needs to be repeated for each muscle; thereby 12 times. 
```
`alpha      = 0.05; 
nTests     = 2;  
p_critical = spm1d.util.p_critical_bonf(alpha, nTests);`
```
Q2C: Knowing that for Hotelling {T2} the average of each muscle for each individual has been used, when post-hoc test is being done: Do we need to use the average EMG for each muscle in every individual (i.e. Groups_A (Muscle1) = [13X100]  and Group_B (Muslce1) =  [11x100])
```
spm       = spm1d.stats.ttest2(Group_A (:,:,1), Group_B(:,:,1)); 
spmi      = spm.inference(0.05, 'two_tailed',true, 'interp',true);
```
OR all trials of each muscle for all subjects need to be included Groups_A_Muscle_1 = [33X100]  and Group_B_Muslce1 =  [88x100]??
```
spm       = spm1d.stats.ttest2(Groups_A_Muscle1, Group_B_Muslce1 ); 
spmi      = spm.inference(0.05, 'two_tailed',true, 'interp',true);
```
Reply to Q3:  **_I think one-way MANOVA would be OK for this analysis._**

Q3A: Is t-test an appropriate post-hoc analysis to find between speed conditions as long as it agrees with the multivariate analysis??


Reply to Q6: >  **_implying a sample size of 390._**
**_implying a sample size of 390._**
I am quite confused about this. Do you mean 390 subjects if I want to use multivariate analysis??
If yes that means It is better to not use the multivariate analysis for any of my tests that I must consider co-variance between the muscles, because I recorded 12 muscles from each subject and the number of subjects is limited due to the nature of the experiment. Am I right (Q6A)?


Q6B: In Group A and Group B in which the total of 24 subjects were recorded and the results seem to be fine (the threshold). Considering the figures attached in Q1, do you think it is statistically correct to consider these results even though the rules of thumb for minimum sample size has not been met?

Parts of my hypothesis was to divide the muscles based on their functional roles and then compare between groups? I think by doing so the number of vector components will reduce and it is justifiable to compare between groups? Am I right (Q6C)?

Q6D As I mentioned above, part of my studies is related to an individual muscle activation rather than inter-muscle covariance or synergistic behavior of the muscles. In that case, if I want to compare the 3 groups which each performed 3 speeds; Which Annova test is appropriate?

Q6E: Do I consider the average trials from each muscle or Include all trials?

Thank you for your valuable time and effort to answer these questions.

**Comment by 0todd0000** [comment] 2017-08-13 00:26
> reply to Q1> _**only insofar as they agree with the multivariate (Hotelling's T2) results. **
> 
> Q1A: Does the above statement mean: When vector field SPM{T2} result shows significance in some regions of the gait cycle it is expected that when post-hoc t-test is performed at least one of the 12 muscles (vector field components) shows the significant difference in the same regions where SPM{T2} supra-threshold cluster occurred?

No.  It means that a linear combination of the 12 muscles will reach significance in the same region(s).  It is possible that no single muscle will reach significance.


> Reply to Q2: > A Sidak / Bonferroni correction, for example, is a good first approximation,
> I used alpha = 0.05 without any correction and results agree with the SPM{T2}, However, I have seen in several papers the alpha level was corrected (sidak /Bonferroni). My question is due to the limitation to do multivariate post hoc, is it justifiable to use the same alpha level (= 0.05) or the correction needs to be implemented (Q2A)?

Some kind of correction must be used.  alpha = 0.05 is not appropriate if alpha = 0.05 was used in the main multivariate test.  A Sidak correction is a reasonable first approximation but generally multivariate *post hoc* procedures should be used.



> if the correction needs to be done then is the following the right procedure (Q2B)? (nTests implies two groups then = 2). The t-test with correct p-critical needs to be repeated for each muscle; thereby 12 times.
 
```
alpha      = 0.05; 
nTests     = 2;  
p_critical = spm1d.util.p_critical_bonf(alpha, nTests);
```

nTests should be 12 if there are 12 muscles.




> Q2C: Knowing that for Hotelling {T2} the average of each muscle for each individual has been used, when post-hoc test is being done: Do we need to use the average EMG for each muscle in every individual (i.e. Groups_A (Muscle1) = [13X100] and Group_B (Muslce1) = [11x100])

The data that were submitted to the main multivariate test should also be submitted to *post hoc* analysis.


> Reply to Q3: I think one-way MANOVA would be OK for this analysis.
> 
> Q3A: Is t-test an appropriate post-hoc analysis to find between speed conditions as long as it agrees with the multivariate analysis??

All *post hoc* analyses are fine provided they do not disagree with the main multivariate results.  The only thoroughly correct *post hoc* procedures are multivariate procedures.

 
> Reply to Q6: > implying a sample size of 390.
> I am quite confused about this. Do you mean 390 subjects if I want to use multivariate analysis??

Sample size = 390.   That could be 390 subjects or 390 observations.

> If yes that means It is better to not use the multivariate analysis for any of my tests that I must consider co-variance between the muscles, because I recorded 12 muscles from each subject and the number of subjects is limited due to the nature of the experiment. Am I right (Q6A)?

If you measure 10N variables, for example, but only have a sample size of N then the experiment is probably quite underpowered.  In other words, the sample size is far too small to convincingly conclude anything about the behaviour of the complex dependent variable.  I'd suggest conducting power analysis before the experiment to determine an appropriate size.


> Q6B: In Group A and Group B in which the total of 24 subjects were recorded and the results seem to be fine (threshold). Considering the figures attached in Q1, do you think it is statistically correct to consider these results even though the rules of thumb for minimum sample size has not been met?

This question is difficult to answer because power analysis was not conducted before the experiment. Had you conducted power analysis and shown that a sample size of 24 was sufficiently large to reach a power of 0.8, for example, then it would be fine to use these results.  Generally power analysis should be conducted to ensure that the sample size matches both (a) the complexity of the dependent variable and (b) the desired effect size.


> Parts of my hypothesis was to divide the muscles based on their functional roles and then compare between groups? I think by doing so the number of vector components will reduce and it is justifiable to compare between groups? Am I right (Q6C)?

If particular muscles are irrelevant to your hypothesis then I think it's fine to exclude them from analysis.  However, a reviewer may ask: if they are irrelevant, then why were they measured?
 
> Q6D As I mentioned above, part of my studies is related to an individual muscle activation rather than inter-muscle covariance or synergistic behavior of the muscles. In that case, if I want to compare the 3 groups which each performed 3 speeds; Which Annova test is appropriate?

A hypothesis which pertains to individual muscle activation assumes that that muscles are independent.  That assumption may or may not be valid.  In general it is not valid, so multivariate procedures should be used.  If there are two factors (group and speed) then two-way MANOVA should be used.  In order to justify use of separate two-way ANOVAs for each muscle you would need to demonstrate inter-muscle independence.

> Q6E: Do I consider the average trials from each muscle or Include all trials?

It depends partly on what your hypothesis is.  If your hypothesis pertains to the population of subjects then using within-subject means is fine.  Including all trials generally improves parameter estimates (e.g. 1D smoothness) but with a relatively large number of subjects you will likely find that ultimate results are similar when using only means.


Todd

**Comment by PouyanMehryar** [comment] 2017-08-16 16:57
Thank you so much, Tod, I really appreciate your help. I have learned so much from your publications and this forum. 
I am sorry to take up your time but I 've got, hopefully, some quick follow up questions:

Following up on my Q3: 
I would like to understand how to organize my data sets:
To prepare for Manova 1D: I have done the following: 
Group_A_slow= [13x100x12] (13 subjects x registered point x 12 muscles)
Group_A_normal = [13x100x12]
Group_A_fast = [13x100x12] 

I have seen in your publication that you included only 1 subject, however, I wanted to see the effect of speeds on the whole population rather than going through Manova1D for each subject separately. 
I combined all speeds in one matrix and assign index to define each subject's speed 
Y_combined = [Group_A_slow; Group_A_normal; Group_A_fast] ; % % Dimension (39x100x12)
A_index = [1x39]; % (1st 13 colomns = 1 (slow), 2nd 13 colomns  = 2 (normal) and 3rd 13 colomns  =3 (fast) 

then I performed Manova1d test. 

3*) I wonder if this is correct way to do it or I need to do Manova for each subject separetely?

3**) I understand as you mentioned above that multivariate post-hoc tests need to be done. I wonder if I could do Hotelling {t2} or hotellings_paired as the post-hoc test with corrected p-value. That is 

`%(1) Conduct SPM analysis:
t21        = spm1d.stats.hotellings2(Group_A_normal, Group_A_slow);
t32        = spm1d.stats.hotellings2(Group_A_fast, Group_A_normal);
t31        = spm1d.stats.hotellings2(Group_A_fast, Group_A_slow);
% inference:
alpha      = 0.05;
nTests     = 3;  
p_critical = spm1d.util.p_critical_bonf(alpha, nTests);
t21i       = t21.inference(p_critical);
t32i       = t32.inference(p_critical);
t31i       = t31.inference(p_critical);`

3:**A: Should I do hotellings_paired or hotellings_{t2} in this scenario?

3**B: I have chosen nTest to be 3 (3 speeds) but do I need to consider the 12 muscles and 3 different speeds (12 muscles x 3 speeds =36)? 

3*** if Hotelling {t2} can't be done, for the post-hoc scaler, even though inter-muscle covariance are not considered, I want to do individual muscle analysis using t-test. what would be the appropriate number of n-Test in this situation (3 or 36)?

3****: If the result shows no significance generally there is no need to do the post-hoc test but sometimes the difference in mean is very close to the threshold. and when the post-hoc test is done the significant can be seen between the two conditions (speeds)? how would you interpret the results in this situation?

I cannot thank you enough for all your help.

**Comment by 0todd0000** [comment] 2017-08-17 07:29
Hi, no problem, thank you for your questions!

> 3*) I wonder if this is correct way to do it or I need to do Manova for each subject separetely?

The data organization looks correct.  The correct experimental model depends what your experimental question is.  If you wish to make inferences regarding the population from which these subjects were drawn then you should include all subjects in the analysis.  If, however, you wish to make inferences regarding the population of trials for each subject then you should analyze each subject separately, with a correction for multiple comparisons (i.e. multiple tests) across subject.

However, please note that the design you describe sounds like it may be a repeated measures design.  If there is a total of 13 subjects, and each performed Slow, Normal and Fast, then the design is repeated measures.  Repeated-measures MANOVA is not yet supported in **spm1d**.


> 3**) I understand as you mentioned above that multivariate post-hoc tests need to be done. I wonder if I could do Hotelling {t2} or hotellings_paired as the post-hoc test with corrected p-value. 

Your code looks good, and paired Hotelling's T2 tests are indeed a good approach if the main design is repeated-measures MANOVA. 


> 3:**A: Should I do hotellings_paired or hotellings_{t2} in this scenario?


If the design is repeated-measures (i.e. N subjects each performed all tasks), then paired tests should be used in *post hoc* analysis.  If the design is not repeated-measures (i.e. 3N subjects participated, with N unique subjects performing each task) then two-sample tests should be used in *post hoc* analysis.


> 3**B: I have chosen nTest to be 3 (3 speeds) but do I need to consider the 12 muscles and 3 different speeds (12 muscles x 3 speeds =36)?

No, the multivariate tests deal with the 12 muscles.  You would only need to consider correcting for multiple comparisons if you do a second-level of *post hoc* tests where you conduct univariate tests (e.g. paired t tests) to examine single muscles in two tasks.



> 3*** if Hotelling {t2} can't be done, for the post-hoc scaler, even though inter-muscle covariance are not considered, I want to do individual muscle analysis using t-test. what would be the appropriate number of n-Test in this situation (3 or 36)?

36 tests.  

3 pairs of conditions [(1) Slow-Normal, (2) Normal-Fast, (3) Slow-Fast]
 x 
12 muscles

However, note that these univariate tests may not relate very closely to the main multivariate experimental results.  For this experiment univariate  paired t tests regard the data as  26 x 100 arrays, and that is a vast simplifications of the measured dataset, which is a 39 x 100 x 12 array. It's fine to conduct t tests to explore possible explanations for the main multivariate result, but those univariate results should be interpreted cautiously.  In general you can do anything you want in *post hoc* analysis provided you regard the main multivariate result as the best description of the experimental outcome.


> 3****: If the result shows no significance generally there is no need to do the post-hoc test but sometimes the difference in mean is very close to the threshold. and when the post-hoc test is done the significant can be seen between the two conditions (speeds)? how would you interpret the results in this situation?

If the main test fails to yield significance then *post hoc* results mustn't be interpreted as significant.  Note that your null hypothesis pertains to the measured dataset (i.e. a 39 x 100 x 12 data array;  all muscles and all tasks).  There are *a priori* hypotheses regarding neither specific muscles nor specific tasks.  If you actually had an *a priori* hypothesis regarding only one muscle and only two tasks, for example, then you would have conducted an experiment in which you measured data from only that muscle and only for those two tasks.  Measuring many muscles in many tasks implies that one is able to conclude little regarding specific muscles and specific tasks relative to an experiment which measures only one muscle in only one or two tasks.  More generally, increased experimental design complexity implies a loss of explanatory power regarding specific design elements.


Todd

**Comment by PouyanMehryar** [comment] 2017-08-18 23:18
Dear Todd 

 (Q1) The reason I can justify to use each muscle separately within the same population and compare between speeds is that parts of my research has an application in robotics (prosthesis control) which individual muscle activation is the focus of study. 
I have done One-way repeated-measures ANOVA (anova1rm) to investigate the within subject differences as well as plotted the between subjects F statistics (using anova1d) at 3 different speeds. I would like to know why within subjects interaction reach significance however the between subjects don’t in some cases (see figure below). 

![image](https://user-images.githubusercontent.com/17261178/29480612-7a093338-8471-11e7-88f4-87526d7fc913.png)

Q2) for the post hoc test, I have done pair t -test and also t- test between the 3 speeds to see the effect of within (anova_rm) and between subjects (anova1), respectively? are these correct post-hoc tests?


Q3) In some cases the F statistics shows significance in some regions of GC but when post hoc test is done no statistical significance has shown. What could be the reason for that ( see figs below)?

Repeated measure anova
![image](https://user-images.githubusercontent.com/17261178/29480799-f894f7ea-8472-11e7-8145-b5e4943eb003.png)

Post hoc pair-t test (bonferroni_p_ value used) 
![image](https://user-images.githubusercontent.com/17261178/29480813-11f6cf2e-8473-11e7-935a-475fb75499f8.png)


Q3A) or sometimes in the main analysis (anova_rm) there are two suprathershold clusters but the post hoc test (pair-t test) between the 3 speeds only shows 1 suprathreshold cluster ( see figure below)?

Repeated measure anova
![image](https://user-images.githubusercontent.com/17261178/29480705-44943c1a-8472-11e7-8fc2-77a0844a8ee4.png)

Post hoc pair-t test (bonferroni_p_ value used) 
![image](https://user-images.githubusercontent.com/17261178/29480695-2d93ab18-8472-11e7-937c-a337257f87f7.png)


Thank you in advance for your response!

**Comment by 0todd0000** [comment] 2017-08-18 23:59
> (Q1) I would like to know why within subjects interaction reach significance however the between subjects don’t in some cases.

Because between- and within-subject effects are different. Consider the following dataset:

Subject | Cond A | Cond B | Cond C
-------- | -------- | -------- | -------- |
1 |  100 | 105 | 110
2 |  200 | 206 | 210
3 |  300 | 304 | 310
4 |  400 | 406 | 409
5 |  500 | 504 | 511

Between-subject analysis (below) shows that mean between-condition differences (5) are small relative to the SD (158).

_ | Cond A | Cond B | Cond C |
-------- | -------- | -------- | -------- | 
Mean | 300 | 305 | 310 |
SD | 158 | 158 | 158 |


Within-subject analysis (below) shows that paired-condition means (5) are large relative to the SD (~1).

_ | Cond (B - A) | Cond (C - B) | Cond (C - A) |
-------- | -------- | -------- | -------- | 
Mean | 5 | 5 | 10 |
SD | 1.0 | 1.6 | 0.7 |


In other words, between-subjects analysis yields a small F value because between-subject variability is  large relative to between-condition variability.  Within-subject analysis yields a large F value because paired effects are large relative to paired variability.


> Q2) for the post hoc test, I have done pair t -test and also t- test between the 3 speeds to see the effect of within (anova_rm) and between subjects (anova1), respectively? are these correct post-hoc tests?

Within-subject ANOVA (i.e. repeated-measures ANOVA) requires within-subject *post hoc* analysis  (i.e. paired t tests).  Between-subject ANOVA (i.e. normal ANOVA) requires between-subject *post hoc* analysis (i.e. two-sample t tests).

> Q3) In some cases the F statistics shows significance in some regions of GC but when post hoc test is done no statistical significance has shown. What could be the reason for that?

Bonferroni *post hoc* procedures are approximate.  Different *post hoc* procedures are needed to yield precise probabilistic agreement between the main analysis and *post hoc* results.  Those procedures are not yet available in **spm1d**. 


> Q3A) or sometimes in the main analysis (anova_rm) there are two suprathershold clusters but the post hoc test (pair-t test) between the 3 speeds only shows 1 suprathreshold cluster?

Same answer as above.  In general please regard *post hoc* analyses as approximate explanations for the main (ANOVA) results.  Where differences exist one mustn't make conclusions that disagree with the main results.


Todd

**Comment by PouyanMehryar** [comment] 2018-01-24 11:00
Dear Tod, 

Summary: recorded EMG from healthy subjects and amputees lower limb. 
my hypothesis pertains to the different group of muscles i.e. quadriceps (RF, VM, VL), hamstrings (BFLH, SEM), dorsiflexion (TA, EX) and plantar flexors ( GM, GL, SOL). 

These subjects performed activities at different speeds. 
I want to know the effect of speeds on quadriceps, hamstrings, dorsiflexion, plantar flexors intra-subjectively and inter-subjectively. 
My null hypothesis is to check if 
1: there is no difference between quadriceps muscles across speeds within the healthy group.
1: there is no difference between hamstrings across speeds within the healthy group.

each one of these groups separetely but I am not sure if I need to correct the alpha considers all 4 groups of muscles.

**Comment by 0todd0000** [comment] 2018-01-24 23:00
QA)  Generally you should (a) correct for the number of *a priori* hypotheses, and (b) only analyze data relevant to those *a priori* hypotheses. Please note that a correction of alpha/N, where N is the number of tests, is approximate.  It's generally better to use a Bonferroni correction.  I agree that the design sounds like two-way RM MANOVA, with a constrained set of *post hoc* comparisons.  That's perfectly fine, and you should follow generally accepted procedures for constrained *post hoc* comparisons.

QB)  Alpha pertains only to the main experiment (i.e. two-way RM MANOVA). You must adopt a corrected threshold in all *post hoc* tests, even in an exploratory study.  Thus c) through e) are clearly incorrect.  a) and b) are tougher, and it is not possible to say what is correct here because the only strictly correct approach is to use multivariate *post hoc* analysis procedures.  Since this is exploratory analysis I'd recommend using everything from an uncorrected alpha=0.05 to a conservative threshold across all *post hoc* possibilities and comparing the results.  If the results are qualitatively affected (i.e. significant for the former but not for the latter) then it would be best to interpret the results cautiously.

**Comment by PouyanMehryar** [comment] 2018-01-25 12:55
Dear Tod, 

I have a general question regarding parametric and non-parametric paired- Hotelling's T2 test.
I performed parametric and non-parametric paired Hotelling's T2 using a Bonferroni corrected alpha (for a) and b). The results are different. Non-parametric reached the threshold however parametric showed no significance.
![pram and non-param](https://user-images.githubusercontent.com/17261178/35389158-81521cce-01ce-11e8-9dfd-f3c53f10f44a.PNG)

Q1) Since non-parametric are always correct Should I just include the results from non- parametric or I should include both?
Q2) Generally, what could be the reasons for the parametric and non-parametric results to be different from each other. 

Thank you in advance for your response!

**Comment by 0todd0000** [comment] 2018-01-26 00:41
Q1)  I'd recommend reporting both, potentially one as supplementary material and explaining why the parametric results differ.
Q2) There are two general reasons:  non-normality, and small sample size.  Parametric and non-parametric results are expected to converge as the data become increasingly normal and as sample sizes get increasingly large.

**Comment by 0todd0000** [comment] 2018-01-26 00:50
(P.S.  Please open new issues, this issue has become too long!)

**Comment by PouyanMehryar** [comment] 2018-01-27 21:16
Dear Tod, 

Sorry to post my question here again! This is much related to what I explained above. I will open a new issue after this. 

I have performed both non-parametric and parametric paired-Hotelling's T2 test using a Bonferroni correction between speeds for each population (as explained above) and the results were different. As recommended, I am going to report both results. One thing that I noticed is that all the p-values calculated from the non-parametric SPM have the value of 0.005. That is, any suprathreshold clusters above the T2* have the same probability i.e. p= 0.005 for all muscles. 

Q1) Is this normal? why is that?

**Comment by 0todd0000** [comment] 2018-01-28 03:02
Q1)  In non-parametric permutation analysis the minimum p value is 1 / (number of permutations).  So you've likely used 2000 permutations, yielding a minimum p value of 1/2000=0.005.  Increasing the number of permutations will yield slightly more accurate p values.

Please also make sure that, when using a Bonferroni-corrected threshold, you also correct the p values as described at the bottom of this page:
http://www.spm1d.org/doc/PostHoc/anova.html

(P.S.  I realize that Q1 is related to the the analyses above, but it would be better to report it as a new issue because we did not discuss this constant p value issue above. If you post is as a new issue with a title like: "constant p values in non-parametric analysis" it will be easier for others to find. Thanks!)
