### ISSUE TITLE
Vector Field analysis

### ISSUE THREAD

**Issue by GuillaumeRao** [0todd0000/spm1dmatlab#27] opened 2016-09-26 15:33 UTC
Dear Todd, 
thanks a lot for sharing this nice SPM package!

We're trying to use and understand (as best as we can) the vector field part. 
Our experiment protocol stands as follow:
3D Ground reaction forces recorded 5 times per subject for 6 different experimental conditions and for 15 subjects. In a first attempt, we've averaged all the trials of each subject for each experimental condition (after time normalizing the data). We've then constructed our input matrix as indicated in the help document, resulting in a 90 x 101 x 3 matrix. 

As given in the example file (ex1d_manova1), we've used the manova1 function (spm1d.stats.manova1), but we're struggling with the interpretation and further post hoc analysis of the results (knowing that post hoc analyses are not developed yet). Is it possible to apply the spm1d.stats.ttest2 function to a 3D matrix (I'd guess no)? 

Consequently, we're wondering whether the outputs of the manova1 function are similar to the one from a vector field analysis. Is it possible to compare multiple experimental conditions resulting in multiple 3D input matrices (as in several experimental conditions resulting in multiple 3D GRF data)? 

What would be your recommendation for the best analysis in this case, as we would like to highlight differences from the experimental conditions?

Thanks a lot in advance for your answer!
Best regards, 
Guillaume

**Comment by 0todd0000** [comment] 2016-09-26 20:11
Hi Guillame,

If the six experimental conditions represent a single factor then a one-way model is correct, and if different subjects performed each of the conditions then one-way MANOVA is correct, but if there is more than one factor (e.g. two levels of a TIME OF DAY factor, three levels of an INTENSITY factor) then a two-way model would be appropriate, and if each subject performed all conditions then a repeated-measures model is needed.  Assuming that there is just one factor with six different levels, and assuming that each subjects performed each of the six conditions, a one-way repeated-measures MANOVA sounds like the appropriate model.  Unfortunately multivariate repeated-measures models are not available in **spm1d** v.0.3.  We plan to release repeated measures multivariate procedures in a future version of the software, but they won't be available for some time.

Assuming that one-way repeated-measures MANOVA is the correct model, the best way to deal with the data using **spm1d** v.0.3 is probably to conduct paired Hotelling's T2 tests on each combination of factor levels using **spm1d.stats.hotellings_paired**.  There are 15 different two-level combinations of those 6 levels, so it would be best to correct for multiple comparisons across these 15 tests using a Bonferroni correction of 0.0034: 

```
>>  alpha = 0.05;
>>  p_critical = spm1d.util.p_critical_bonf(alpha, 15);   %0.0034
```

Note that a Bonferroni correction is generally more conservative than the correction which MANOVA would apply, so results which fail to reach significance but which approach the critical threshold should be interpreted cautiously.


> As given in the example file (ex1d_manova1), we've used the manova1 function (spm1d.stats.manova1), but we're struggling with the interpretation and further post hoc analysis of the results (knowing that post hoc analyses are not developed yet). Is it possible to apply the spm1d.stats.ttest2 function to a 3D matrix (I'd guess no)?

That's correct:  **spm1d.stats.ttest2** is a univariate procedure.  The multivariate equivalent of two-sample t test is a two-sample Hotelling's T2 test (**spm1d.stats.hotellings2**), but if this is a repeated measures design you should use paired tests instead of two-sample tests.

> Consequently, we're wondering whether the outputs of the manova1 function are similar to the one from a vector field analysis. Is it possible to compare multiple experimental conditions resulting in multiple 3D input matrices (as in several experimental conditions resulting in multiple 3D GRF data)?

The **spm1d.stats.manova1** does conduct a vector field analysis.  As a terminology note:
* scalar data = univariate data
* vector data = multivariate data

In **spm1d** the main univariate procedures include:
* t tests
* regression
* ANOVA

whose multivariate equivalents are:
* Hotelling's T2 tests
* Canonical correlation analysis (CCA)
* MANOVA

To answer your question: interpretations of results from multivariate (vector field) procedures are identical to their univariate counterparts.  If significance is reached in a two-sample t test, for example, it implies that *univariate 1D Gaussian data* would produce the same result in less than alpha% of an infinite number of identical experiments.  If significance is reached in a two-sample Hotelling's T2 test, it implies that *multivariate 1D Gaussian data* would produce the same result in less than alpha% of an infinite number of identical experiments.  Thus ANOVA and MANOVA have the same basic interpretation, the only thing that changes is the nature of the underlying data (univariate vs multivariate).

Todd

**Comment by GuillaumeRao** [comment] 2016-09-27 11:22
Hi Todd, 
thanks a lot for this very informative answer!
It's much more clear now. 
We'll test and get back to you if necessary. 
Best regards, 
Guillaume

**Comment by 0todd0000** [comment] 2016-09-27 20:19
No problem Guillaume.  I'll close this issue for now, but please feel free to continue a conversation regarding vector field analysis on this page.  Otherwise feel free to create a new issue.
Todd

**Closed by 0todd0000** 2016-09-27 20:19 UTC

**Comment by GuillaumeRao** [comment] 2016-09-28 12:42
Hi Todd,
thanks a lot once again for your answer, I think we’ve understood the global functioning of the spm package.
If I’m correct, and based on the paper you’ve published in JEK in 2015, we could be able to perform a vector field analysis on more that 3 components (let’s say 10 EMG traces) to compare different experimental conditions (let’s start with 2 for simplicity)?
As an output, we could get an idea of whether (and at what time) the global EMG « coordination » (as in a synergy approach) differs between the condition.
Are we correct with this kind of reasoning or are the Hotellings tests limited to 3D input matrices?
Once again, thanks a lot for your help!
Guillaume


[cid:E6C80DA2-2D99-4E8F-9679-C71C1292DB7F]

Guillaume Rao - Resp. Scientifique TechnoSport, Resp. CMI Ingénierie du Mouvement Humain -
UMR 7287.Sc. du Mouvement (EJ Marey)
Institut des Sciences du Mouvement - 163 Avenue de Luminy - 13009 Marseille
Tél: +33(0)4 91 17 04 22 - Mobile : +33(0)6 84 13 69 77
Site : http://www.univ-amu.fr<http://www.univ-amu.fr/> - Email : guillaume.rao@univ-amu.fr<mailto:guillaume.rao@univ-amu.fr>
Afin de respecter l'environnement, merci de n'imprimer cet email que si nécessaire.

Le 27 sept. 2016 à 22:19, Todd Pataky <notifications@github.com<mailto:notifications@github.com>> a écrit :


No problem Guillaume. I'll close this issue for now, but please feel free to continue a conversation regarding vector field analysis on this page. Otherwise feel free to create a new issue.
Todd

**Comment by 0todd0000** [comment] 2016-09-28 23:28
Hi Guillaume,


> If I’m correct, and based on the paper you’ve published in JEK in 2015, we could be able to perform a vector field analysis on more that 3 components (let’s say 10 EMG traces) to compare different experimental conditions (let’s start with 2 for simplicity)?
> As an output, we could get an idea of whether (and at what time) the global EMG « coordination » (as in a synergy approach) differs between the condition.

Yes that's correct.  Since muscles tend to behave non-independently, it may be a good idea to combine them in a single multivariate analysis.  I think "global EMG" is probably a good way to think about it, but "net EMG effect" or "combined EMG effect" or "multi-muscle EMG effect" may also be appropriate.


> Are we correct with this kind of reasoning or are the Hotellings tests limited to 3D input matrices?
> Once again, thanks a lot for your help!

Yes, Hotelling's tests are multivariate tests so require multivariate data.  If you consider an array with size:  (_J x Q x I_)  where:
_J_ = number of observations
_Q_ = number of 1D continuum nodes
_I_ = number of vector components (e.g. number of muscles)

then the data are univariate if _I_ = 1 and are multivariate if _I_ > 1.  Note that _I_ must be greater than 1 for multivariate procedures.  

After conducting Hoteling's T2 tests, you may wish to conduct post hoc t tests on each of the _I_ components separately, using a Bonferroni correction to correct for the _I_ separate post hoc tests.  This Bonferroni correction is generally a bit too conservative, but will at least help you to interpret the results of Hoteling's T2 tests, and in particular which muscle(s) and/or combinations of muscles are most likely contributing to the multivariate effect.

Todd

Todd

**Comment by GuillaumeRao** [comment] 2016-09-29 07:43
Hi Todd,
thanks a gain a lot for this very informative answer, we're ready to test everything!
Best regards,
Guillaume
[cid:E6C80DA2-2D99-4E8F-9679-C71C1292DB7F]

Guillaume Rao - Resp. Scientifique TechnoSport, Resp. CMI Ingénierie du Mouvement Humain -
UMR 7287.Sc. du Mouvement (EJ Marey)
Institut des Sciences du Mouvement - 163 Avenue de Luminy - 13009 Marseille
Tél: +33(0)4 91 17 04 22 - Mobile : +33(0)6 84 13 69 77
Site : http://www.univ-amu.fr<http://www.univ-amu.fr/> - Email : guillaume.rao@univ-amu.fr<mailto:guillaume.rao@univ-amu.fr>
Afin de respecter l'environnement, merci de n'imprimer cet email que si nécessaire.

Le 29 sept. 2016 à 01:28, Todd Pataky <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hi Guillaume,

If I’m correct, and based on the paper you’ve published in JEK in 2015, we could be able to perform a vector field analysis on more that 3 components (let’s say 10 EMG traces) to compare different experimental conditions (let’s start with 2 for simplicity)?
As an output, we could get an idea of whether (and at what time) the global EMG « coordination » (as in a synergy approach) differs between the condition.

Yes that's correct. Since muscles tend to behave non-independently, it may be a good idea to combine them in a single multivariate analysis. I think "global EMG" is probably a good way to think about it, but "net EMG effect" or "combined EMG effect" or "multi-muscle EMG effect" may also be appropriate.

Are we correct with this kind of reasoning or are the Hotellings tests limited to 3D input matrices?
Once again, thanks a lot for your help!

Yes, Hotelling's tests are multivariate tests so require multivariate data. If you consider an array with size: (J x Q x I) where:
J = number of observations
Q = number of 1D continuum nodes
I = number of vector components (e.g. number of muscles)

then the data are univariate if I = 1 and are multivariate if I > 1. Note that I must be greater than 1 for multivariate procedures.

After conducting Hoteling's T2 tests, you may wish to conduct post hoc t tests on each of the I components separately, using a Bonferroni correction to correct for the I separate post hoc tests. This Bonferroni correction is generally a bit too conservative, but will at least help you to interpret the results of Hoteling's T2 tests, and in particular which muscle(s) and/or combinations of muscles are most likely contributing to the multivariate effect.

Todd

Todd
