### ISSUE TITLE
anova2onerm versus anova2rm

### ISSUE THREAD

**Issue by FluxEline** [0todd0000/spm1dmatlab#49] opened 2017-06-14 10:23 UTC
Hi Todd and colleagues,

Last year I used anova2rm to perform a two-factor anova. I wanted to analyse differences between 3 patient groups (6 at each measurement site) and differences between 3 models. In this design, only the factor ´models´ is repeated measures and ´measurement site´ is not.

Within the anova2rm you insert the data, the first factor, the second and the subject numbers. With the new update, anova2onerm also exists. This indicates (if I understand correctly) that only one factor (and this should be the first one) is repeated.  

When adding the value 'subject', you would assume that all information is provided to the ANOVA. E.g. the ANOVA should recognize that none of the subjects are measured at more than 1 measurement site, and therefore no repeated measures can be performed over this factor. Therefore I would expect quite similar results from both analyses, or an error when you use anova2rm, since subjects are only measured at one of the measurement sites and therefore repeated measures for two factors are not performed. 
Nevertheless I find large differences when using anova2rm or anova2onerm. I was wondering how this is possible.

With kind regards,
Eline Flux

**Comment by 0todd0000** [comment] 2017-06-14 20:51
Hi Eline,

If you use **anova2onerm** then subject labels are regarded as separate for each level of the first factor (Factor A).  Consider the following table:

[Table 1]

| Group A1 | Group A2 |
| --------- | --------- |
| Subject 1 | Subject 1 |
| Subject 2 | Subject 2 |
| ... | ... |
| Subject N | Subject N |



For this subject labeling, **anova2onerm** regards Subject 1 in Group A1  as different from Subject 1 in Group A2.  In contrast, **anova2rm** regards Subject 1 in Groups A1 and A2 as the same person.  Thus, for **anova2onerm**, Table 1 above is equivalent to Table 2 below.

[Table 2]

| Group A1 | Group A2 |
| --------- | --------- |
| Subject 1 | Subject N+1 |
| Subject 2 | Subject N+2 |
| ... | ... |
| Subject N | Subject N+N |


However, if you try to use Table 2 labeling for **anova2rm** you should receive an error because not all subjects are represented in all levels of Factor A.  If you have some MATLAB code that uses Table 2 labeling and **anova2rm**, and which does not produce an error then please send it;  that would be a big software bug and I'll need to fix it.

Thanks!
Todd

**Comment by FluxEline** [comment] 2017-06-15 07:22
Hi Todd,

Thank you for the fast and clear explanation. I would have thought that when using  anova2onerm subject labels are regarded as separate for each level of the _second_ factor (Factor B). But I now indeed see that it is programmed differently. But also for this case, I would have though that ANOVA would now which one is repeated by the input of the subject parameter. But considering your explanation, I understand correctly that it automatically 'renumbers' the subject information, which yields different results.

Included I attach my dataset of several (time normalised) gait cycles and the two factors A and B, of which only A is a repeated measures. When I run the anova2rm from the newest download, I do not receive an error. I do receive the error when I run the anova2rm from the example data of anova2onerm. 

The only thing I can imagine giving a problem is that I have 3 measures per subject per condition, whereas the example data hasn't. 

Curious as to your findings.

[Uploading Flux_ANOVA2RM_Data.mat…]()

Thanks!
Eline Flux

**Comment by FluxEline** [comment] 2017-06-16 10:25
[Flux_ANOVA2RM_Data.zip](https://github.com/0todd0000/spm1dmatlab/files/1080482/Flux_ANOVA2RM_Data.zip)

**Comment by 0todd0000** [comment] 2017-06-17 02:58
Hi Eline,
That is indeed a bug in the software, thank you for finding it!!
Please give me a day or two to fix it.  I'll write again when the update is ready.
Todd

**Comment by 0todd0000** [comment] 2017-06-19 04:22
Hi Eline,

The bug has been patched!  Please download the new version of the code (version M0.4.4) and try again.  The new version should generate an "unbalanced design" error when trying to use the data you attached above along with **spm1d.stats.anova2rm**.

The bug was caused by a careless coding error:  a single line of code failed to stop the search for unbalanced factor levels once one was found.  I'm very sorry for this error!  And thank you so much for discovering it!!!

Todd

P.S.  This bug is not relevant to the Python version of **spm1d**, which correctly reports unbalanced design errors.

**Comment by FluxEline** [comment] 2017-06-21 08:10
Hi Tod,

Thank you for your fast responses. I downloaded the new version. Could it however be that I get the unbalanced error too much at the moment? When using the anova2onerm for a three-factor design I get this error. When using the ex1d_anova2onerm I also get this error when using the dataset: spm1d.data.uv1d.anova2onerm.SPM1D_ANOVA2ONERM_3x3();

Best, Eline

**Comment by 0todd0000** [comment] 2017-06-22 02:00
Hi Eline,

Thank you for spotting that!  I've fixed that error too so now all of the **anova2onerm** datasets should be fine. Please download the new version at your convenience:  version 0.4.5 (2017.06.22).


Please note:

- The new errors were caused by my improper design balance checks.  The actual ANOVA code, including F statistic computation, is OK.

- These annoying design balance checks will go away in a future version of **spm1d** once unbalanced designs are better supported. For now, thank you for your patience!

- Although not directly related to your question, please note that **anova2onerm** supports unbalanced designs in the following sense:   there can be different numbers of subjects for different levels of Factor A.  Thus a design like the one below is OK.

| Group A1 | Group A2 |
| --------- | --------- |
| Subject 1 | Subject 1 |
| Subject 2 | Subject 2 |
| ... | ... |
| Subject N-2 | Subject N-2 |
| Subject N-1 |  |
| Subject N |  |


Todd

**Comment by FluxEline** [comment] 2017-07-12 06:55
Hi Todd,

Perfect it is working again. I think there only might be one more bug. In your example data, you only have 1 measure of each condition. In my study I have 3 trials for each condition. When using anoova2onerm on my data, I don't get an error that the data is unbalanced, even when it should be unbalanced. So that is when I insert a repeated condition as the first input and a non-repeated measure as the second input. For my data this is no problem, but you might want to take a look at it.

It is perfect that the unbalanced design with different subject numbers works! Thank you for taking a look at it.

Best, Eline

**Comment by 0todd0000** [comment] 2017-07-16 00:02
Hi Eline,

Sorry for my delayed reply, and thank you for reporting the bug!

I've been trying to reproduce the problem but I'm unable to because I don't quite understand where the imbalance exists ...

Can you please send the contents of the three input vectors (A, B and SUBJ)?

Todd

**Comment by 0todd0000** [comment] 2017-08-18 22:24
Hi Eline,
I'm going to close this issue but please feel free to re-open it if the problem hasn't been resolved.
Todd

**Closed by 0todd0000** 2017-08-18 22:24 UTC
