### ISSUE TITLE
Significant effects at the begining and the end of the stance phase

### ISSUE THREAD

**Issue by NicolasFlores14** [0todd0000/spm1dmatlab#37] opened 2016-11-15 14:56 UTC
Dear Todd Pataky,

Thanks for the informations provided in all issues.

I have trouble to understand a main effect from an ANOVArm.

Some significant effects appeared at the begining and at the end of the signal as you can see on the picture below. I took precautions during the signal processing by filtering first before to cut my signal. The stance phase was identified when the force was above the threshold of 10N and the cutting was performed then. Theorically, differences couldn't appeared here, no ?

![anovarm](https://cloud.githubusercontent.com/assets/23238495/20310353/f74f6f92-ab4b-11e6-9d9d-bdcda1bb9d0b.png)

Thanks a lot for your help,
Best regards.

Nicolas Flores

**Comment by jwvrente** [comment] 2016-11-16 10:04
Dear Nicolas,

When first seeing the issue that you raise I would have thought that this could have been a filtering artefact, but considering that you filtered before cutting your signal I no longer expect such.

First, I am uncertain of whether you are presenting F-curves or t-curves in the above. Can you confirm that you ran a two-way repeated measures ANOVA, with factor and modality as two independent variables? If that is the case, then I would expect the curves that you present to be posthoc analyses and hence t-curves.

Second, the averages don't differ much, yet your F-curves exceed the threshold considerably (particularly in the left one). Would it be possible to plot the SD clouds to somehow verify that your results are not spurious effects somehow?

Kind regards,
Jos

**Comment by NicolasFlores14** [comment] 2016-11-16 11:02
Dear Jos,

Thanks for your answer.

Effectively I performed a two-way repeated measures ANOVA. Therefore GRF curves above are not associated with the F curves (but with both posthoc tests on the factors A and B respectively, as you mentioned in your post). Please find below the GRF curve with SD clouds and the F-curve associated for the main effect A: 
![curves](https://cloud.githubusercontent.com/assets/23238495/20344024/4d480a6c-abf1-11e6-8c62-20719ccf9939.jpg)
![f-curve](https://cloud.githubusercontent.com/assets/23238495/20344060/6d515926-abf1-11e6-8bec-652e06b4eed7.jpg)

For more clarity, the focus on the significant cluster between 98.97% and 100% on the GRF curve and the F-curve:
![curvesend](https://cloud.githubusercontent.com/assets/23238495/20344800/754fb23c-abf4-11e6-9ceb-2cd9975adeaf.JPG)
![f-curveend](https://cloud.githubusercontent.com/assets/23238495/20344808/79689708-abf4-11e6-9717-0ba480736c27.JPG)


Also for more clarity here is the posthoc analysis performed on the factor A:
![posthoca](https://cloud.githubusercontent.com/assets/23238495/20344440/10b16a6a-abf3-11e6-9682-6a1e0c526a8d.JPG)

And the significant cluster between 98.26% and 100% with a focus:
![posthocaendcurve](https://cloud.githubusercontent.com/assets/23238495/20344354/b5062f5c-abf2-11e6-943e-5049eec57327.JPG)

Thank you so much for your help.

Nicolas

**Comment by jwvrente** [comment] 2016-11-16 11:34
Hi Nicolas, 

That is very enlightening, thanks. Based on the variation in your data, and the rather small differences between your conditions, I am still a little surprised by the size of your effects. Nonetheless, I would like to assume that you have run the tests appropriately, so I would immediately wonder what your sample size was?

The issue of the results at the start/end of your data is still unexplained, and I can only wonder if the threshold criterion could systematically lead to a difference between conditions. Considering that you take a threshold of 10N, it means first of all that the values of the first/last data point in your time series is skewed, with the highest concentration of values close to 10N. However, if in one condition for example the loading rate at that point in time were higher, then it could be that those first/last values are systematically higher, and that this causes the difference. Although small to see, it appears that in your last graph (zooming in on posthoc on the factor A) the variation of the light blue condition shifts further downwards than that of the grey condition, and it seems to happen only for the last data point. The fact that the effect already appears from 98.4% is expected to be a consequence of interpolation more than anything else, and I think the culprit is the very first/last value in the time series. So my suggestion would be to look into whether the very first/last value of your data series may well be affected by the thresholding, i.e. whether the thresholding leads to systematically different values in one compared to another condition. That is the only thing I can currently think of. Hope that helps.
Regards,
Jos

**Comment by 0todd0000** [comment] 2016-11-16 21:58
Hi Nicolas,

Jos' comments prompted one other thought:  since this is a repeated-measures design the within-subject differences are more important than the group means, so I'd suggest plotting mean *differences*.

For example, if there are twenty subjects and your data look like this:

```
A1B1 = randn(20, 101);
A1B2 = randn(20, 101);
A2B1 = randn(20, 101);
A2B2 = randn(20, 101);
```

Then instead of computing Condition A means like this:

```
meanA1 = mean( [A1B1; A1B2] , 1 );
meanA2 = mean( [A2B1; A2B2] , 1 );
```

Try computing and plotting within-subject differences like this:

```
A1diffs = A1B1 - A1B2;
A2diffs = A2B1 - A2B2;

meanA1diff = mean( A1diffs, 1 );
meanA2diff = mean( A2diffs, 1 );

sdA1diffs = std( A1diffs, 1 );
sdA2diffs = std( A2diffs, 1 );

close all
plot( meanA1diff, 'linewidth', 3, 'color', 'k' )
hold on
plot( meanA1diff + sdA1diffs, 'linewidth', 0.5, 'color', 'k' )
plot( meanA1diff - sdA1diffs, 'linewidth', 0.5, 'color', 'k' )

plot( meanA2diff, 'linewidth', 3, 'color', 'r' )
plot( meanA2diff + sdA2diffs, 'linewidth', 0.5, 'color', 'r' )
plot( meanA2diff - sdA2diffs, 'linewidth', 0.5, 'color', 'r' )
```

It's possible that between-subject variability is large, and that the variability of within-subject differences is comparatively small.

Todd

**Comment by NicolasFlores14** [comment] 2016-11-17 10:17
Dear Jos and Todd,

Thanks for the time you take to find a solution.

Jos: 
I tried to keep the signal above a 20N threshold. The significant effect at the end disappears. It could be due to the loss of the signal between 10N and 20N, which was significant previously. However, the significant effect remains at the beginning of the anteroposterior component of the GRF. Maybe the threshold is still too weak... Or maybe these effects are "true" effects, which are due to my experimental conditions and they need to be interpreted. 

Todd:
I perform the code you sent me. I have 19 participants with 5 trials per condition, therefore my matrices A1B1, A1B2, A2B1 and A2B2 have 95 rows and 101 columns. Is it ok ?

If it is, here is the plot corresponding: 
![plotbsws](https://cloud.githubusercontent.com/assets/23238495/20385289/30f387bc-acb7-11e6-8566-19b54d3803c3.JPG)

Thanks for your answers.

Nicolas

**Comment by 0todd0000** [comment] 2016-11-17 21:56
Hi Nicolas,

Data arrays sized (95 x 101) should be no problem. However, I think I made a mistake in the code I suggested above.  Could you also try the within-A differences like below?  That should look more like the Main Effect A figure at the top of this issue.

```
A1   = [A1B1; A1B2];
A2   = [A2B1; A2B2];

Adiffs = A1 - A2;
meanAdiffs = mean(Adiffs, 1);
sdAdiffs = std(Adiffs, 1);

plot(meanAdiffs, 'k', 'linewidth', 3)
hold on
plot(meanAdiffs - sdAdiffs, 'k', 'linewidth', 0.5)
plot(meanAdiffs + sdAdiffs, 'k', 'linewidth', 0.5)
```


Todd

**Comment by NicolasFlores14** [comment] 2016-11-18 09:04
Dear Todd,

Please find the new figure with the new code:
![plotbsws2](https://cloud.githubusercontent.com/assets/23238495/20424462/494fccf2-ad76-11e6-9a94-e16c3815a4d9.JPG)

Thanks !

Nicolas

**Comment by 0todd0000** [comment] 2016-11-19 03:27
Hi Nicolas, that looks much more like the main effect of A in the figure at the top of this issue.  The calculation is not quite right --- it would probably be better to first compute within-subject means --- but I think that this at least explains why you're seeing such a big signal in the main effect of A.

You may also want to try plotting the mean difference (as in the figure above) divided by the standard deviation;  that should more closely follow the main effect of A.

However, that doesn't resolve potential data processing issues, which as Jos suggests may be responsible for the signal at the beginning / end.  I would follow Jos's advice and try a range of reasonable processing parameters, and then report whether or not your results are sensitive to those parameter changes.

Todd

**Comment by 0todd0000** [comment] 2016-12-08 00:46
Hi Nicolas,  I'll close this issue for now, but please feel free to re-open it if the problem is not resolved.  Todd

**Closed by 0todd0000** 2016-12-08 00:46 UTC
