### ISSUE TITLE
Anova2onerm issue: Error warning

### ISSUE THREAD

**Issue by Antoine-Cht** [0todd0000/spm1dmatlab#158] opened 2021-11-30 13:42 UTC
Dear Todd

I try to compare force signal between two groups (controls n=29, vs. patients n=29) at 7 different measurement time (At rest, fatigue n°1 : fatigue n°6, where an individual performs all the measurements). I read that the anova2onerm is the appropriate design: 
spmlist   = spm1d.stats.anova2onerm(Y, A, B, SUBJ)

I organized my data as recommended by the example in spm1d matlab folder:

Y = matrix data 406 x 200 (each row is an individual at different measurement = 58 * 7)
A = groups 1 x 406 represented as [0,0,0,0,0,0, … 1,1,1,1,1,1,1]
B = conditions 1 x 406 represented as [1,1,1,1,1,…2,2,2,2,…..7,7,7,7,7,7]
SUBJ = subjects 1 x 406 represented as [1,2,3,4,5,6,7,8,9,10, … 55,56,57,58]

I try also as recommended in the issue #146 with column format, 
Y = 406 x 200
A = 406 x 1
B = 406 x 1
SUBJ = 406 x 1

But I continue to have the following message: 

_

> _Error using  * 
> Incorrect dimensions for matrix multiplication. Check that the number of columns in the first matrix
> matches the number of rows in the second matrix. To perform elementwise multiplication, use '.*'.
> 
> Error in spm1d.stats.anova.LinearModel/aov (line 91)
>             SS = contrasts.C * effects.^2;
> 
> Error in spm1d.stats.anova2onerm (line 16)
> SPM    = model.aov(design.contrasts, design.f_terms);
> 
> Error in Z_RFD_SPM_11_2021v7 (line 169)
> spmlist   = spm1d.stats.anova2onerm(Y, A, B, SUBJ);_

_

I verified the size of the input and they are correct, so I don't know where the problem come from, any idea ?

Thank you very much for your help.
AC

**Comment by Antoine-Cht** [comment] 2021-11-30 15:40
Edit : Despite different groups set in A = [0;0;0;0;0;0;1;1;1;1;1;1]
I  specified the same ID within each group A = [0;1;2;3;4;5;0;1;2;3;4;5], whereas they need to be different [0;1;2;3;4;5;6;7;8;9;10;11]

*false alert*

**Comment by 0todd0000** [comment] 2021-12-02 12:17
Sorry for the delayed response!  By "false alert" I gather that the issue is resolved, so I will close this issue. Please feel free to re-open this issue if needed.

**Closed by 0todd0000** 2021-12-02 12:17 UTC

**Comment by Antoine-Cht** [comment] 2021-12-02 13:35
Hello todd,

Yes the issue is resolved, I didn't well code the subject numbers.

I would like to tell you thank you very much for your work (and your
collegues) regarding SPM applied in the biomechanical field ! This helping
us a lot and we publish a paper few month ago regarding 2-D SPM analysis in
diabetic plantar pressure in Diabetic Medicine journal. Just for sharing
because you contributed indirectly

Best regards


*Antoine Chatrenet *

Ph D. Student

Laboratoire Motricité Interactions Performance (MIP) EA4334

CH du Mans : Néphrologie - Plateforme de Recherche Clinique

SFP-APA : Responsable de la commission Néphrologie

***@***.***

[image: Site du laboratoire Motricité Interactions Performance (MIP)]
<https://staps.univ-nantes.fr/recherche/ea-4334-motricite-interactions-performance-572067.kjsp>



***@***.***

[image: Site du Centre Hospitalier du Mans] <https://www.ch-lemans.fr/>



***@***.***

[image: Site de la Société Française des Enseignants en Activité Physique
Adaptée] <https://www.sfp-apa.fr/>


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le jeu. 2 déc. 2021 à 13:17, Todd Pataky ***@***.***> a
écrit :
