### ISSUE TITLE
Two-Way ANOVA Interpretation

### ISSUE THREAD

**Issue by t-thorsen** [0todd0000/spm1dmatlab#157] opened 2021-11-16 17:51 UTC
I have designed a 2x2 [Group x Condition] two-way Anova with 50 subjects. 

Group A / Group B with Walking Condition 1 and Walking Condition 2. All data were time-normalized to 100% of stance (101 data points). 

I used spm1d.stats.anova2(Dataset,Y,subjects,conditions) to test differences between groups and conditions. The results were:
- non-significant Main Effect A
- one supra-threshold cluster for Main Effect B. The supra-threshold cluster for Main Effect B is during an unusual time in the gait cycle for the data. 
- non-significant AB interaction. 

Interestingly, if I run a paired samples t-test between the 2 gait conditions (effectively testing Main Effect B), spm1d.stats.ttest_paired(Condition_1, Condition_2) the results indicate 2 supra-threshold clusters that are located in the regions of the stance phase that make sense with what the discrete literature has reported (i.e. peak moments or GRFs). 

My specific question is regarding the interpretation of the SPM ANOVA. With a traditional 0D discrete analysis, I would simply report Main Effect B for this particular variable. I am curious what the correct interpretation of the SPM 1D Main Effect B is given the seemingly “odd” location of the supra-threshold cluster – compared to the seemingly “normal” supra-threshold clusters that are found from the paired samples t-test. Can you explain why there might be temporal differences between supra-threshold clusters from the ANOVA compared to the t-test? 

Any help or advice would be greatly appreciated. Thanks in advance and thank you for such through source codes and documentation!

**Comment by 0todd0000** [comment] 2021-12-16 03:46
Sorry for the long delay!  For some reason I accidentally missed this issue earlier...

Most generally:  *post hoc* t tests do not necessarily follow ANOVA results. *Post hoc* results should be used **only** to qualify the main ANOVA results.

In this case, partial disagreement in the Condition 1 vs. 2 comparison may be caused by a number of factors. Here are two:

- Repeated measures (RM): `ttest_paired` is an RM test, but `anova2` is not. If each individual performed the two conditions, and if the two groups consist of different individuals, then `anova2onerm` would be more appropriate.

- Non-reduced threshold:  the critical p value in *post hoc* analysis must be less than alpha. It should be reduced mainly based on the number of possible *post hoc* comparisons. In this case, trying a critical p value of 0.025 (and not alpha=0.05) may yield results which agree better with the ANOVA results.


If these two points do not resolve (or largely resolve) the disagreement between the *post hoc* and main ANOVA results, then please write again, preferably with figures and/or your code which shows how you reduced the dataset for *post hoc* analysis.

**Comment by t-thorsen** [comment] 2021-12-20 22:05
Thanks for getting back! Let me first start by addressing the first bullet point. In my original post, I realized a typo. I did in fact originally use anova2onerm(Dataset,Y,subjects,conditions). My apologies.  

I have uploaded 3 figures. The first is the results of the anova2onerm{F} test. Main A (Between Subjects) Main B (Between Conditions) and the Interaction. I have also uploaded figures from the ttest_paired results Between conditions. The waveforms of compressive force are panel A, the SPM{t} results are panel B. 

I followed your suggestion and reduced the p-value of the ttest_paired to 0.025. From the figures below you'll see that it changed the p-values slightly, but the overall supra-threshold clusters are still similar in nature. 

I am still a little confused why there is such a difference between the regions of significance from 'Main B' on the interaction figure to those of the ttest_paired figures. In essence, both of those figures are representing comparisons between Condition 1 and Condition 2. Thanks for your help!
![Interaction_GitHub](https://user-images.githubusercontent.com/94478040/146838716-83874d9c-1ff6-453d-a858-42235d0355bb.jpg)
![Condition_ttest_05_GitHub](https://user-images.githubusercontent.com/94478040/146838731-cb45490c-9168-4662-97cc-d9196ba7e98e.jpg)
![Condition_ttest_025_GitHub](https://user-images.githubusercontent.com/94478040/146838743-26e014d8-1796-4834-b488-abf104296543.jpg)

**Comment by 0todd0000** [comment] 2021-12-22 01:30
I agree that these results do not make sense. Can you please attach the script used to generate these results?

**Comment by t-thorsen** [comment] 2021-12-22 14:53
Hi Todd,

Thank you for taking a look at this. Here is the script I used, with a few added notes. By way of reference, I am using MATLAB R2021a.

% These are the variables used, and how they are created. 
% Y = [100x101] Has column for each observation, 50 subjects, 2 conditions
% each. 
% A = [1x100] assigns condition label for each condition. A(1:50 = 0) for
% walking condition 1, A(51:100) = 1 for walking condition 2. 
% B = [1x100] with alternating 0 and 1, representing each walking condition
% for each subject. 
% SUBJ = 2 columns for each subject number. Created as follows:
% for i=1:50,SUBJ = [SUBJ (i-1) (i-1)];end 

%% Interaction 

% Normality test
alpha     = 0.05;
spm       = spm1d.stats.normality.anova2(Y, A, B);
spmi      = spm.inference(0.05);
disp(spmi)
norm_name = ['Interaction_' var '_' condition '_Normality Results.mat'];
% save(norm_name,'spmi');

% Normality Test Plot
% close all
figure('position', [0 0  1200 300])
subplot(131);  plot(Y', 'k');  hold on;  title('Data')
subplot(132);  plot(spm.residuals', 'k');  title('Residuals')
subplot(133);  spmi.plot();  title('Normality test')

% Repeated Measures ANOVA SPM
spmlist   = spm1d.stats.anova2onerm(Y, A, B, SUBJ);
spmilist_Interaction  = spmlist.inference(0.05);
disp_summ(spmilist_Interaction)
spmilist_Interaction.plot('plot_threshold_label',false, 'plot_p_values',true, 'autoset_ylim',true);
saveas(gcf,int_filename);
anova_name = ['Interaction_' var '_' condition '_Results.mat'];
% save(anova_name,'spmilist_Interaction');

%% Test of Main A SPM{t} - Between Subjects
% All Group A vs. All Group B
spm = spm1d.stats.ttest2(GroupA,GroupB);
spmi_Main_A_R_NR = spm.inference(0.05, 'two_tailed', true, 'interp',true);  
disp(spmi_Main_A_R_NR)

figure ('Name','Main Effect A - Between Subjects');
subplot(321)
spm1d.plot.plot_meanSD(GroupA, 'color','k');
hold on
spm1d.plot.plot_meanSD(GroupB, 'color','r');
title('GroupA vs. GroupB')
box off
ylabel([var ' (BW)'])
subplot(322)
spmi_Main_A_R_NR.plot();
spmi_Main_A_R_NR.plot_threshold_label();
spmi_Main_A_R_NR.plot_p_values();
title('Hypothesis test')

%% Test of Main B SPM{t} - Within Subjects
% All Condition 1 vs. Condition 2
spm = spm1d.stats.ttest_paired(C1,C2);
spmi_Main_B_C1_C2 = spm.inference(0.05, 'two_tailed', true, 'interp',true);  
disp(spmi_Main_B_C1_C2)

figure ('Name','Main Effect B - Within Subjects');
subplot(121)
a = spm1d.plot.plot_meanSD(C1, 'color','k');
hold on
b = spm1d.plot.plot_meanSD(C2, 'color','r');
legend([a b],'C1','C2')
legend box off
title('A')
box off
ylabel([var ' (BW)'])
xlabel('Time (% Stance)')

subplot(122)
spmi_Main_B_C1_C2.plot();
spmi_Main_B_C1_C2.plot_threshold_label();
spmi_Main_B_C1_C2.plot_p_values();
title('B')
xlabel('Time (% Stance)')

**Comment by 0todd0000** [comment] 2021-12-22 15:11
**Request 1**:  Please confirm whether `SUBJ` is a vector (i.e., a single-column array). It should be a vector, and not a two-column array.

**Request 2**:  Please explain `C1` and `C2`.

**Request 3**:  Please confirm whether the following snippet is an adequate summary of the two figures (ignoring variable definitions and figure decorations).

```octave
spmlist = spm1d.stats.anova2onerm(Y, A, B, SUBJ);
spmilist_Interaction = spmlist.inference(0.05);
spmilist_Interaction.plot('plot_threshold_label',false, 'plot_p_values',true, 'autoset_ylim',true);


% Post hoc: Condition 1 vs. Condition 2
spm = spm1d.stats.ttest_paired(C1,C2);
spmi_Main_B_C1_C2 = spm.inference(0.05, 'two_tailed', true, 'interp',true);

figure ('Name','Main Effect B - Within Subjects');
subplot(121)
a = spm1d.plot.plot_meanSD(C1, 'color','k');
hold on
b = spm1d.plot.plot_meanSD(C2, 'color','r');
legend([a b],'C1','C2')

subplot(122)
spmi_Main_B_C1_C2.plot();
spmi_Main_B_C1_C2.plot_threshold_label();
spmi_Main_B_C1_C2.plot_p_values();
```

**Comment by 0todd0000** [comment] 2021-12-22 15:15
**Request 4**:  Please assemble `A`, `B` and `SUBJ` into a single array like this:

```octave
X = [A B SUBJ];
disp( X )
```
and then please copy the contents of `X` into this thread.

**Comment by t-thorsen** [comment] 2021-12-22 16:11
**Request 1:** Yes, `SUBJ `is a 1x100 vector. When I wrote that it was 2 columns for each subject number, what I meant was that there were two cells, [0 1], for each subject number. The variable `SUBJ `is a 1x100 vector and so each cell is in a different column.  
**Request 2:** `C1 `and `C2` are two different walking conditions. In this particular case, they are two different slopes. 
**Request 3:** The snippet you provided seems to match the code I have for the figures. 
**Request 4:** Here are the contents of `X`
`>>
 X = [A B SUBJ];
disp( X )

  Columns 1 through 24

     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0

  Columns 25 through 48

     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0

  Columns 49 through 72

     0     0     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1

  Columns 73 through 96

     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1     1

  Columns 97 through 120

     1     1     1     1     0     1     0     1     0     1     0     1     0     1     0     1     0     1     0     1     0     1     0     1

  Columns 121 through 144

     0     1     0     1     0     1     0     1     0     1     0     1     0     1     0     1     0     1     0     1     0     1     0     1

  Columns 145 through 168

     0     1     0     1     0     1     0     1     0     1     0     1     0     1     0     1     0     1     0     1     0     1     0     1

  Columns 169 through 192

     0     1     0     1     0     1     0     1     0     1     0     1     0     1     0     1     0     1     0     1     0     1     0     1

  Columns 193 through 216

     0     1     0     1     0     1     0     1     0     0     1     1     2     2     3     3     4     4     5     5     6     6     7     7

  Columns 217 through 240

     8     8     9     9    10    10    11    11    12    12    13    13    14    14    15    15    16    16    17    17    18    18    19    19

  Columns 241 through 264

    20    20    21    21    22    22    23    23    24    24    25    25    26    26    27    27    28    28    29    29    30    30    31    31

  Columns 265 through 288

    32    32    33    33    34    34    35    35    36    36    37    37    38    38    39    39    40    40    41    41    42    42    43    43

  Columns 289 through 300

    44    44    45    45    46    46    47    47    48    48    49    49

>> `

**Comment by 0todd0000** [comment] 2021-12-24 00:45
OK, thank you for your answers.

Regarding **Request 2**: please send code which indicates how `C1` and `C2` were calculated.

Regarding **Request 4**: Can you please convert `A`, `B` and `SUBJ` to column vectors then re-send the contents of `X`?  `X` should be a `(J,3)` array, where  `J` is the number of observations. This can be achieved like this:

```octave
X = [A' B' SUBJ'];
```

**Comment by t-thorsen** [comment] 2021-12-29 01:25
Todd,

My apologies for the delayed response. 

**Request 3:**`C1 `and `C2 `were each organized as a 50x101 matrix with Group A observations for the first 25 rows and Group B observations for the last 25 rows. For `C1`, for example, Rows 1:25 are observations from Group A during walking condition 1, and rows 26:50 are observations from Group B during walking condition 1. `C2 `is organized similarly, just with observations from walking condition 2. 

**Request 4:**

```
X = [A' B' SUBJ']

X =

     0     0     0
     0     1     0
     0     0     1
     0     1     1
     0     0     2
     0     1     2
     0     0     3
     0     1     3
     0     0     4
     0     1     4
     0     0     5
     0     1     5
     0     0     6
     0     1     6
     0     0     7
     0     1     7
     0     0     8
     0     1     8
     0     0     9
     0     1     9
     0     0    10
     0     1    10
     0     0    11
     0     1    11
     0     0    12
     0     1    12
     0     0    13
     0     1    13
     0     0    14
     0     1    14
     0     0    15
     0     1    15
     0     0    16
     0     1    16
     0     0    17
     0     1    17
     0     0    18
     0     1    18
     0     0    19
     0     1    19
     0     0    20
     0     1    20
     0     0    21
     0     1    21
     0     0    22
     0     1    22
     0     0    23
     0     1    23
     0     0    24
     0     1    24
     1     0    25
     1     1    25
     1     0    26
     1     1    26
     1     0    27
     1     1    27
     1     0    28
     1     1    28
     1     0    29
     1     1    29
     1     0    30
     1     1    30
     1     0    31
     1     1    31
     1     0    32
     1     1    32
     1     0    33
     1     1    33
     1     0    34
     1     1    34
     1     0    35
     1     1    35
     1     0    36
     1     1    36
     1     0    37
     1     1    37
     1     0    38
     1     1    38
     1     0    39
     1     1    39
     1     0    40
     1     1    40
     1     0    41
     1     1    41
     1     0    42
     1     1    42
     1     0    43
     1     1    43
     1     0    44
     1     1    44
     1     0    45
     1     1    45
     1     0    46
     1     1    46
     1     0    47
     1     1    47
     1     0    48
     1     1    48
     1     0    49
     1     1    49
```

**Comment by 0todd0000** [comment] 2021-12-29 03:18
Based on your description everything sounds fine. So I am still unsure what is causing the problem.

I suggest we aim for a simple-as-possible script that (i) starts from an empty workspace, and (ii) replicates the problem. If we a have a simple-as-possible script like this, it will be easier to debug. The script should do the following:
- Clear the workspace
- Load the data
- Calculate `C1` and `C2`
- Display all array sizes
- Conduct the ANOVA test
- Conduct the *post hoc* test
- Plot the ANOVA results
- Plot the *post hoc* results
- ... and nothing else (i.e., no normality tests, no extra plots, no extra plotting commands, etc.)


The script should look something like this:

```octave

% clear workspace
clear
close all

% load data
load( myMATfile )  % contains 'Y', 'A', 'B' and 'SUBJ'

% calculate C1 and C2
C1 = ...
C2 = ...

% display all array sizes:
disp( size(Y) )
disp( size(A) )
disp( size(B) )
disp( size(SUBJ) )
disp( size(C1) )
disp( size(C2) )

% conduct ANOVA
spmlist = spm1d.stats.anova2onerm(Y, A, B, SUBJ).inference(0.05);

% conduct post hoc analysis
spm_posthoc = spm1d.stats.ttest_paired(C1,C2).inference( 0.05/3, 'two_tailed', true, 'interp',true );

% plot ANOVA
figure
spmilist.plot();

% plot post hoc results
figure
spm_posthoc.plot();
```


Please modify this script as needed, then please copy all outputs (array sizes and figures) into your reply.

**Comment by t-thorsen** [comment] 2021-12-29 04:30
Todd, 

I am including the output you have requested below, with one notable change. Our dataset _now_ has 50 participants. When I began this thread with the initial SPM ANOVA, I was using a slightly smaller subset (n=44) of collected participants. I did not realize we would get this detailed with this code (...but thank-you!), and so I am reverting to the exact data set I used to generate the figures from the first post. I have included an updated `X` output as well. All other information is the same, with just n=44. 

```
>> disp(X)
     0     0     0
     0     1     0
     0     0     1
     0     1     1
     0     0     2
     0     1     2
     0     0     3
     0     1     3
     0     0     4
     0     1     4
     0     0     5
     0     1     5
     0     0     6
     0     1     6
     0     0     7
     0     1     7
     0     0     8
     0     1     8
     0     0     9
     0     1     9
     0     0    10
     0     1    10
     0     0    11
     0     1    11
     0     0    12
     0     1    12
     0     0    13
     0     1    13
     0     0    14
     0     1    14
     0     0    15
     0     1    15
     0     0    16
     0     1    16
     0     0    17
     0     1    17
     0     0    18
     0     1    18
     0     0    19
     0     1    19
     0     0    20
     0     1    20
     0     0    21
     0     1    21
     1     0    22
     1     1    22
     1     0    23
     1     1    23
     1     0    24
     1     1    24
     1     0    25
     1     1    25
     1     0    26
     1     1    26
     1     0    27
     1     1    27
     1     0    28
     1     1    28
     1     0    29
     1     1    29
     1     0    30
     1     1    30
     1     0    31
     1     1    31
     1     0    32
     1     1    32
     1     0    33
     1     1    33
     1     0    34
     1     1    34
     1     0    35
     1     1    35
     1     0    36
     1     1    36
     1     0    37
     1     1    37
     1     0    38
     1     1    38
     1     0    39
     1     1    39
     1     0    40
     1     1    40
     1     0    41
     1     1    41
     1     0    42
     1     1    42
     1     0    43
     1     1    43

>> disp( size(Y) )
    88   101

>> disp( size(A) )
     1    88

>> disp( size(B) )
     1    88

>> disp( size(SUBJ) )
     1    88

>> disp( size(C1) )
    44   101

>> disp( size(C2) )
    44   101
```
![SPM_Testing_ANOVA](https://user-images.githubusercontent.com/94478040/147627443-50988274-9860-4ecd-b205-87eec054d917.jpg)
![SPM_Testing_posthoc](https://user-images.githubusercontent.com/94478040/147627446-24fc7991-a55f-4cc2-9213-bbc8c568ee20.jpg)

**Comment by 0todd0000** [comment] 2021-12-29 14:15
Thank you. Can you please copy your script too, including the `C1` and `C2` calculations?

**Comment by t-thorsen** [comment] 2021-12-29 16:28
Here is my script - 

The original data, `Data`, is organized in a data structure that contains data for Group A and Group B. Each group's data is stored as a 101x30x22 three-dimensional array with 101 data points x 30 variables x 22 subjects in each group. For this analysis, we are obviously only using 1 variable of the 30. So, to calculate C1 and C2 I first have to reorganize these data. I have copied the script below, and attached the .mat file to this reply as well. 

Again, I greatly appreciate you taking the time to sort this out with me. 
[SPM_Testing.zip](https://github.com/0todd0000/spm1dmatlab/files/7789772/SPM_Testing.zip)


```
% clear workspace
clear
close all

% load data
load( 'SPM_Testing.mat' )  % contains 'Y', 'A', 'B' and 'SUBJ' and 'Data', the original data structure. 

X = [A' B' SUBJ'];

% calculate C1 and C2

% Variable 'c' identifies the specific column of the variable within the three-dimensional array. 
c = 2; 
GroupA_C1 = squeeze(Data.GroupA.Ten(:,c,:)); 
GroupB_C1 = squeeze(Data.GroupB.Ten(:,c,:)); 

GroupA_C2 = squeeze(Data.GroupA.Level(:,c,:)); 
GroupB_C2 = squeeze(Data.GroupB.Level(:,c,:)); 

GroupA = [GroupA_C1, GroupA_C2]';
GroupB = [GroupB_C1, GroupB_C2]';

C2 = [GroupA_C2,GroupB_C2]';
C1 = [GroupA_C1,GroupB_C1]';

% display all array sizes:
disp(X)
disp( size(Y) )
disp( size(A) )
disp( size(B) )
disp( size(SUBJ) )
disp( size(C1) )
disp( size(C2) )

% conduct ANOVA
spmlist = spm1d.stats.anova2onerm(Y, A, B, SUBJ).inference(0.05);

% conduct post hoc analysis
spm_posthoc = spm1d.stats.ttest_paired(C1,C2).inference( 0.05/3, 'two_tailed', true, 'interp',true );

% plot ANOVA
figure
spmlist.plot();

% plot post hoc results
figure
spm_posthoc.plot();
```

**Comment by 0todd0000** [comment] 2021-12-29 20:06
That's clearer, thanks! And I apologize for my lack of clarity: please ensure that C1 and C2 are calculated from Y, A, B, and/or SUBJ.

In the current script it is possible that C1 and C2 contain different data from Y. I'd like to rule out this possibility as a sanity check, and I'd also like to clarify the relationships amongst all of these variables. Your descriptions are clear, but there may have been an earlier coding error which disrupted the mapping from Y to C1 and C2, so I'd like to rule out this possibility.

**Comment by t-thorsen** [comment] 2022-01-03 18:00
Using the script that you provided above (and that I have been modifying along the way), I would calculate Y as follows `Y = [GroupA;GroupB];`. This is how I interpreted the 'stacked groups' description found in the documentation [online](https://spm1d.org/doc/Stats1D/anova.html#label-stats-anova). It sounds to me like you are suggesting `Y = [C1;C2];`?

**Comment by t-thorsen** [comment] 2022-01-12 22:05
Hi Todd,

I think my issue might stem from the construction of my variables `A`, `B`, `SUBJ`, and `Y`. I discovered this when I was studying the example dataset provided with the spm1d download, ex1d_anova2onerm.m. 

The example data set appears to be a 2x2 ANOVA with 5 subjects in each group, with a single observation for each subject in each of the 2 repeated factors, for a total of 20 observations. 

To pull from that data set, variables  `A`, `B`, `SUBJ`, and `Y` are provided in a structure as follows:

`A = 0	0	0	0	0	0	0	0	0	0	1	1	1	1	1	1	1	1	1	1`
`B = 0	0	0	0	0	1	1	1	1	1	0	0	0	0	0	1	1	1	1	1`
`SUBJ = 0	 1	2	3	4	0	1	2	3	4	5	6	7	8	9	5	6	7	8	9`

We do not know how the variable Y was organized in the example dataset, however, I assume an organizational framework for Y (a 20 x 101 matrix) may look like this:

`Y = GroupA_Factor_1;
       GroupA_Factor_2;
       GroupB_Factor_1;
       GroupB_Factor_2;`
Where the two groups are stacked on top of each other, and, within each group, the two different repeated measures are stacked on top of each other. 

Am I understanding this framework correctly? More importantly, is this the _only_ way for the code to correctly map all of the variables together? 

This is not how I originally structured my variables. I suspect the way I had structured my variables may be causing the confusing results that originally led to me posting on this forum. For ease of understanding in this post, I will use the same n=5 to demonstrate my original framework: 

`A_mydata = 0	 0	0	0	0	0	0	0	0	0	1	1	1	1	1	1	1	1	1	1`
`B_mydata = 0	 1	0	1	0	1	0	1	0	1	0	1	0	1	0	1	0	1	0	1`
`SUBJ_mydata = 0	0	1	1	2	2	3	3	4	4	5	5	6	6	7	7	8	8	9	9`
`Y_mydata = GroupA_Factor_1;
       GroupA_Factor_2;
       GroupB_Factor_1;
       GroupB_Factor_2;`

Moreover, when I rearranged `A` `B` and `SUBJ` in my original data, it produced results that seem to make more sense. Compare the SPM output I have attached here with the timeseries plots that I attached earlier (they are Panel A, with the red and gray shaded standard deviations).  

Sorry for the long post! If you can offer any advice or counsel on my thoughts here, I would greatly appreciate it! 








![SPM_Testing_ANOVA_NEW](https://user-images.githubusercontent.com/94478040/149230230-671590c6-ed7c-4f03-b1b2-2ebc15acdd49.jpg)

**Comment by 0todd0000** [comment] 2022-01-13 07:51
> Am I understanding this framework correctly?

Yes.

> More importantly, is this the only way for the code to correctly map all of the variables together?

No. The rows of the data array can be shuffled arbitrarily, provided all `A`, `B` and `SUBJ` values are also shuffled accordingly. The `A_mydata`, `B_mydata` and `SUBJ_mydata` values above all look fine. However, the `Y_mydata` does not look fine. Consider `GroupA_Factor_1`. From this variable name, it sounds like this variable should contain all observations corresponding to `A=0` and `B=0`. However, from `B_mydata` it is clear that this is not the case;  `B_mydata` contains both `B=0` and `B=1`.

**Comment by t-thorsen** [comment] 2022-01-20 16:18
Todd,

This last response has answered my question. I believe the conflicting results I was seeing was because of improper setup of variables A, B, Y, and SUBJ. Now that I have fixed that, I am confident in my results. I greatly appreciate all of the help and time you have taken to walk through this with me!

**Comment by 0todd0000** [comment] 2022-01-21 01:00
You're very welcome!  I'll close this issue for now, but please feel free to re-open it or create a new issue if anything else comes up.

**Closed by 0todd0000** 2022-01-21 01:00 UTC
