### ISSUE TITLE
Linear regression analysis.

### ISSUE THREAD

**Issue by Jayishni** [0todd0000/spm1dmatlab#40] opened 2017-01-17 00:28 UTC
I am seeking some advice regarding the use of statistical parametric mapping for linear regression analysis.

In our current project, we have been using the SPM-1d software package to understand the association between muscle and joint mechanics. To our understanding, the software for linear regression analysis only allows the independent variable to be an array containing J scalars. Would you be aware of any work arounds or alternative approaches that would allow us to to perform a linear regression analysis between two variables so that the dependent variable is a (J x Q) array and the independent variable is also a (J x Q) array. 

I would really appreciate any advice or suggestions you may have on this matter.

Kind Regards,
Jayishni

**Comment by 0todd0000** [comment] 2017-01-17 10:41
Hi Jayishni,

That's a very good question, and one that raises many issues!  Your interpretation of the existing **spm1d** functionality is correct:  the type of analysis you describe is not currently supported.  The only way it would be supported is if the independent and dependent variables have the same units and can meaningfully be subtracted from each other, and then assessed using a t test.  For example, if the (J x Q) independent variable represents *J* separate theoretical predictions of kinematic trajectories, and the (J x Q) dependent variable represents the corresponding measured kinematic trajectories, then I think it would be fine to subtract the theoretical values from the measured values and conduct a t test.

However, since you have been looking at regression I expect that the situation is not so straightforward.  If the independent variable does not have the same units as the dependent variable and/or if they cannot be meaningfully subtracted from each other, then I believe the question you're looking to answer is:  at each of the *Q* continuum points, how are the *J* predictor values correlate with the *J* response values?

This type of analysis is probably best described as a generalised linear model (not to be confused with: general linear model), and while not supported in **spm1d**, it is thoroughly supported in  **SPM12** and previous versions of **SPM**:
http://www.fil.ion.ucl.ac.uk/spm/software/spm12/
In fact, **SPM** was originally developed exactly for this purpose. The predictor variables in functional imaging form a (J x Q) matrix, with values spanning *Q* voxels in 3D space, which is I believe quite similar to the situation you describe.  While **SPM12** does indeed support this type of analysis, the bad news is that it is designed to handle 3D data in a particular format, so using **SPM12** for 1D data analysis requires a bit of data and MATLAB finessing, along with a fairly decent understanding of **SPM12**'s underlying MATLAB code.

The reason that **spm1d** doesn't support this type of analysis is that the necessary code is rather difficult to develop.  Specifically, to implement this type of analysis one must overcome the technical challenge of accounting for serial correlations / intrinsic autocorrelations in the data.  This issue is summarized at the link below, and an internet search for *statistical parametric mapping* and *serial correlations* should produce a number of articles which describe the problem.
http://www.fil.ion.ucl.ac.uk/spm/doc/intro/#_B_Serial_correlations_and%20filtering

There are currently no plans to implement this functionality in **spm1d**, but there are plans to implement a MATLAB interface to existing **SPM** packages including **SPM12** and **SPM8**.  That interface would at least allow you to harness the much-more powerful functionality contained in the **SPM** package, but it would still require a decent understanding of **SPM** to be able to extract and interpret results appropriately.

Todd

**Comment by 0todd0000** [comment] 2017-02-03 23:01
Hi again Jayishni,
I'm closing this issue for now, but if anything additional comes up please feel free to re-open this issue or create a new one.
Thanks!
Todd

**Closed by 0todd0000** 2017-02-03 23:01 UTC

**Comment by Jayishni** [comment] 2017-02-05 23:01
Hi Todd,

Thank you for you initial quick response - it was very informative.
Sorry, I never replied. I read you response and delved into reading about SPM.
Kind Regards,
Jayishni

On Feb 4, 2017, at 9:01 AM, Todd Pataky <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi again Jayishni,
I'm closing this issue for now, but if anything additional comes up please feel free to re-open this issue or create a new one.
Thanks!
Todd
